### ISSUE TITLE
Outdated docker-compose.yml

### ISSUE THREAD

**Issue by dodikvt** [boyney123/garie-lighthouse#13]
Looks like something has been change in the name of docker registry, also config.json is not loaded. 

```
version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  garie-lighthouse:
    image: "garie/lighthouse:latest"
    volumes:
      - ./config.json:/usr/src/garie-lighthouse/config.json
      - ./reports:/usr/src/garie-lighthouse/reports
    ports:
      - 3000:3000
    environment:
      - HOST=influxdb 
```
